stages:
  - build
  - docker
  - deploy

DOCKER_TLS_CERTDIR: ""
DOCKER_HOST: tcp://docker:2375/

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/
  policy: pull-push



docker-build:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker build -t docker.io/$DOCKERHUB_USER/tiran:${CI_COMMIT_SHA} .
    - docker push docker.io/$DOCKERHUB_USER/tiran:${CI_COMMIT_SHA}
  only:
    - main
  tags:
    - docker


deploy:
  stage: deploy
  script:
    - echo "=== DEPLOY TO K8S (Docker Hub / public repo) ==="
    - export KUBECONFIG=/home/gitlab-runner/.kube/config
    - kubectl config set-context --current --namespace=mamad
    - envsubst < k8s/manifest.yaml | kubectl apply -f -
    - kubectl get ingress tiran-ingress -n mamad || kubectl apply -f k8s/ingress.yaml
    - kubectl rollout status deployment/tiran-app --timeout=300s
  only:
    - main
  tags:
    - shell