export const galleryItems = [
  {
    id: 1,
    image: "/assets/images/fade3.jpg",
    title: "لوستر کریستالی مدرن",
    description: "طراحی خاص برای فضاهای لاکچری",
    className: "col-span-2 row-span-2",
    link: "/products/crystal-modern",
  },
  {
    id: 2,
    image: "/assets/images/fade4.jpg",
    title: "چراغ‌های دیواری",
    description: "نورپردازی هنرمندانه",
    className: "col-span-1 row-span-1",
    link: "/products/crystal-modern",
  },
  {
    id: 3,
    image: "/assets/images/fade3.jpg",
    title: "لوستر LED",
    description: "تکنولوژی مدرن در روشنایی",
    className: "col-span-1 row-span-2",
    link: "/products/crystal-modern",
  },
  {
    id: 4,
    image: "/assets/images/fade3.jpg",
    title: "آباژور کلاسیک",
    description: "زیبایی در سادگی",
    className: "col-span-2 row-span-1",
    link: "/products/crystal-modern",
  },
  {
    id: 5,
    image: "/assets/images/fade1.jpg",
    title: "لوستر سقفی",
    description: "طراحی منحصر به فرد",
    className: "col-span-1 row-span-1",
    link: "/products/crystal-modern",
  },
  {
    id: 6,
    image: "/assets/images/fade3.jpg",
    title: "چراغ‌های پایه‌دار",
    description: "ترکیب هنر و نور",
    className: "col-span-1 row-span-2",
    link: "/products/crystal-modern",
  },
  {
    id: 7,
    image: "/assets/images/fade4.jpg",
    title: "لوستر مینیمال",
    description: "سادگی در اوج زیبایی",
    className: "col-span-2 row-span-1",
    link: "/products/crystal-modern",
  },
];
